# Generated by Django 4.1 on 2022-08-18 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_reservation_remove_bici_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='from_date',
            field=models.DateTimeField(verbose_name='date from'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='ranking',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='to_date',
            field=models.DateTimeField(verbose_name='date to'),
        ),
    ]
